### ISSUE TITLE
是否这个SDK不支持Net4.6框架编译？

### ISSUE THREAD

**Issue by lihongzhai** [tencentyun/cos-donet-sdk-v4#1]
我克隆代码，修改代码中的AppID，SECRET_ID，SECRET_KEY，bucketName为我账户里的内容，，COSAPI_CGI_URL改成"http://tj.file.myqcloud.com/files/v2/"，其它未作任何修改
然后编译，运行，结果不断得到异常，不能连通服务器！

经过捕获内部异常为：
Message	"远程服务器返回错误: (403) 已禁止。"	string
堆栈：
   在 System.Net.HttpWebRequest.GetResponse()
   在 QCloud.CosApi.Common.Request.SendRequest(String url, Dictionary`2& data, HttpMethod requestMethod, Dictionary`2& header, Int32 timeOut, String localPath, Int64 offset, Int32 sliceSize) 
位置 C:\Users\RoyLi\Source\Repos\cos-donet-sdk-v4\cos_dotnet_sdk\Common\Request.cs:行号 134

控制台输出：
{"code":-96,"message":"ERROR_PROXY_AUTH_EXPIRED","request_id":"NThkOWM3NDlfNmViMjM1XzczOGZfODAxM2I="}

整个过程唯一的可疑之处是我是用Net4.6.1框架编译的。难道这个SDK不支持Net4.6框架编译？求官方解答。

**Comment by ghost** [comment]
V4版本要比V3版本多了一个地域选择，-96建议是把签名的过期时间设长点，根据字段expired的说明来调整一下。
https://www.qcloud.com/document/product/436/6271#.E7.94.9F.E6.88.90.E7.AD.BE.E5.90.8D5

**Comment by lihongzhai** [comment]
地域选择我改成了
华北：http://tj.file.myqcloud.com/files/v2/

我将CosCloud下的时间相关的设置变成原来的10倍，但是还是不好用，改成了最大值7776000也是一样。

//用户计算用户签名超时时间
const int SIGN_EXPIRED_TIME = 1800;

**Comment by ghost** [comment]
这个还建议查一下服务器的时间与北京时间是否同步了呢？

**Comment by lihongzhai** [comment]
改成90天也不行，感觉不是时间同步的问题
我看了时间的算法，都会统一到相对本地的Unix时间上，这个算法应该没有问题

BTW，我机器时间是美东时间。

能否释放一个编译好的控制台测试程序，参数从文本中读取，这样就能很快排除是否代码问题，以及是否是编译问题。

**Comment by lihongzhai** [comment]
刚才又做了几个测试，

重新生成了密钥，也包括项目密钥>>> 新密钥都是同样不行
在华东区生成了bucket，使用华东区，创建文件目录这个测试居然返回不同结果：
{"code":-5999,"message":"ERROR_CGI_PARAM","request_id":"NThkYTc1NTVfYzM0NDNfNDliOV8yNWE0N2Q="}

生成新项目，新bucket>>> 同样返回403。。。

**Comment by ghost** [comment]
-5999检测一下您的参数是否正确配置呢？您的SDK运行环境时间与北京时间不一致吗？

**Comment by ghost** [comment]
根据您提供的信息，这边通过后台查询，发现确实是因为运行环境时间与北京时间不同步的原因导致的，请求的时间的北京时间10点15分，但是签名中的时间，是北京时间11:15到11:18，开始时间是这下图中的方法计算的，您可以看下这个时间对不对。
![image](https://cloud.githubusercontent.com/assets/16502508/24441941/6e6ad76e-148e-11e7-89ae-1fed82fbe2c1.png)

**Comment by lihongzhai** [comment]
SDK运行的时区是美东，因为机器就在美东。纽约时间和北京时间相差了11个小时，这个就和服务器日志对上了。开始时间是你贴出来的算法，我没有改。

不清楚服务器是如何判断请求时间的，但是如果这样，程序在美国运行，SDK就会失效。。。最好还是修改下服务器端的判断逻辑。

看都改成UTC标准时间再进行判断是不是更好一点？

**Comment by kitmanzheng** [comment]
.Net 4.6 is fine for it . And the bug of expire time  had fixed
