### ISSUE TITLE
sign 签名算法中涉及到的expire和current time时间戳问题及解决方案 -59 ERROR_PROXY_S3_AUTH_EXPIRED

### ISSUE THREAD

**Issue by rainsnowclowd** [tencentyun/cos-donet-sdk-v4#6]
今天用这个SDK做创建目录测试的时候一直返回-59 ERROR_PROXY_S3_AUTH_EXPIRED错误。
问题及解决方案如下（懒得往git上提交代码）
1. CosCloud.cs中getExpiredTime 使用DateTime.Now.ToUnixTime() 获取的时间戳是本地时区的时间戳应该为DateTime.Now.ToUniversalTime().ToUnixTime()
2. Sign.cs 中获取now存在同样的问题。

**Comment by kitmanzheng** [comment]
fixed it
